feat: OPX-3.1.0-dev2
open-switch/opx-nas-ndi pull request #23
Opened 2018-11-16 21:03 UTC by GarrickHe

* Feature: Buffer Statistics Tracking (BST)

Signed-off-by: Garrick He <garrick_he@dell.com>

2018-11-19 20:15 UTC, GarrickHe commented
Pull-request updated, HEAD is now 0bc7501455e619439579c4ce4289ef60ed204c3f

2018-11-19 23:27 UTC, rakeshdatta requested changes

2018-11-19 23:27 UTC, rakeshdatta commented on src/nas_ndi_qos_buffer_pool.cpp
> + * @deprecated since 7.7.0
since 7.7.0+opx1?

2018-11-19 23:27 UTC, rakeshdatta commented on src/nas_ndi_qos_priority_group.cpp
> + * @deprecated since 7.7.0
since 4.8.0+opx1?

2018-11-19 23:27 UTC, rakeshdatta commented on src/nas_ndi_qos_priority_group.cpp
> + * @deprecated since 7.7.0
since 7.7.0+opx1?

2018-11-19 23:27 UTC, rakeshdatta commented on src/nas_ndi_qos_queue.cpp
> + * @deprecated since 7.7.0
since 4.8.0+opx1?

2018-11-19 23:27 UTC, rakeshdatta commented on src/nas_ndi_qos_queue.cpp
> + * @deprecated since 7.7.0
since 7.7.0+opx1?

2018-11-19 23:27 UTC, rakeshdatta commented on src/nas_ndi_qos_queue.cpp
> + * @deprecated since 7.7.0
since 7.7.0+opx1?

2018-11-19 23:27 UTC, rakeshdatta commented on debian/changelog
> +  * Feature: Buffer Statistics
Plz add the detailed changelog as discussed offline

2018-11-20 01:48 UTC, atanu-mandal submitted a review, later dismissed

2018-11-20 07:02 UTC, GarrickHe commented
Pull-request updated, HEAD is now 8c768b88c9807b245a18da72b3dc5b81f07d2dce

2018-11-20 07:45 UTC, rakeshdatta approved these changes

2018-11-20 18:06 UTC, atanu-mandal approved these changes

2018-11-21 19:28 UTC, merged