feat: OPX-3.2.0
open-switch/opx-nas-ndi pull request #25
Opened 2019-06-13 22:10 UTC by Tejaswi-Goel

* Update: Set SAI flag on vlan api
* Update: NAS/NDI does not need to be aware of the SAI Default group
* Bugfix: To achieve flexible trap management packet queue need
        to be supported at trap group level instead of at trap level

Signed-off-by: Tejaswi Goel <Tejaswi_Goel@Dell.com>

2019-06-14 21:59 UTC, rakeshdatta requested changes

2019-06-14 21:59 UTC, rakeshdatta commented on configure.ac
> +AC_INIT([opx-nas-ndi], [5.4.0], [ops-dev@lists.openswitch.net])
5.4.0 from 4.8.0??

2019-06-14 21:59 UTC, rakeshdatta commented on inc/opx/nas_ndi_router_interface_utl.h
> + * Copyright (c) 2018 Dell Inc.
change copyright plz

2019-06-14 21:59 UTC, rakeshdatta commented on src/nas_ndi_router_interface_utl.cpp
> + * Copyright (c) 2018 Dell Inc.
copyright plz

2019-06-14 21:59 UTC, rakeshdatta commented on src/unit_test/nas_ndi_ipmc_ut.cpp
> + * Copyright (c) 2018 Dell Inc.
change copyright plz

2019-06-17 16:50 UTC, Tejaswi-Goel commented
Pull-request updated, HEAD is now 193739a075850ab030014e72b167b22981a0f4cb

2019-06-17 19:47 UTC, rakeshdatta approved these changes

2019-06-18 19:15 UTC, merged